import pandas as pd
from matplotlib import pyplot as plt

'''
    Program for Visualisation of Covid-Data generated by scraper.py
    Author: Philippos Maximos Giavridis
'''

if __name__ == "__main__":
    filename = input("Enter the name of your .csv file or '1' for default: ")
    if filename == "1":
        data = pd.read_csv("covid_data.csv")
    else:
        try:
            data = pd.read_csv(filename)
        except FileNotFoundError:
            print("That file does not exist.")
